language: r
sudo: false
cache: packages
warnings_are_errors: true

matrix:
  include:
    - os: linux
      dist: xenial
      r: release
      env: DIST=xenial
    - os: linux
      dist: xenial
      r: devel
      env: DIST=xenial
    - os: linux
      dist: trusty
      r: release
      env: DIST=trusty
    - os: osx
      r: release
    - os: windows
      r: release
  allow_failures:
    - os: osx
    - os: windows

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

r_github_packages:
  - jimhester/lintr

addons:
  apt:
    packages:
      - libcurl4-gnutls-dev
      - libgit2-dev
      - libssl-dev
      - libudunits2-dev
      - libprotobuf-dev
      - libv8-dev
      - libjq-dev
      - protobuf-compiler
      - libgdal-dev

r_packages:
  - covr
  - lintr
  - roxygen2
  - pkgdown

script:
  - R CMD build .
  - R CMD check *tar.gz

after_script:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'roxygen2::roxygenise()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  github_token: $GITHUB_TOKEN             # Set in travis-ci.org dashboard
  local_dir: docs                         # Deploy the docs folder
  on: # Only deploy if master branch, xenial build and with latest released version of R.
    branch: master
    dist: xenial
    r: release

notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always 
